version: '3'

services:
  gqlgen_app:
    build: .
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PAGE_LIMIT=${PAGE_LIMIT}
      - ORDER_BY=${ORDER_BY}
    ports:
      - ${PORT}:${PORT}
    network_mode: host
    command: ./gqlgenExample